

rbac:
  create: true

cull:
  enabled: true
  timeout: 120        # Pod-ul se închide la 2 minute după ce devine complet inactiv (fără browser deschis ȘI fără kernel activ)
  every: 30           # Verifică starea la fiecare 30 de secunde
  maxAge: 86400       # Limita absolută de 24 de ore în secunde. După acest timp, pod-ul se închide forțat, chiar dacă încheie calcule
  users: false        # Închide doar pod-ul, nu deloghează utilizatorul din Hub

hub:
  config:
    JupyterHub:
      admin_users:
        - stefan

  nodeSelector:
    kubernetes.io/hostname: stefan-zenbook-ux425ua-um425ua
  
  extraConfig:
    # --- INSTALARE ȘI CONFIGURARE COMPLETĂ ---
    00-init-native-auth: |
      import subprocess
      import sys
      import sqlite3

      # 1. Instalare pachet
      try:
          import nativeauthenticator
      except ImportError:
          subprocess.check_call([sys.executable, "-m", "pip", "install", "jupyterhub-nativeauthenticator"])

      # 2. Configurare Authenticator
      c.JupyterHub.authenticator_class = 'nativeauthenticator.NativeAuthenticator'
      c.NativeAuthenticator.enable_signup = True
      c.NativeAuthenticator.open_signup = True
      c.NativeAuthenticator.minimum_password_length = 8


      c.Authenticator.allow_all = True


    # --- LIMITELE TALE DE RESURSE ---
    resource_limits: |
      def custom_limits(spawner):
          spawner.start_timeout = 300
          spawner.environment['JUPYTERHUB_ACTIVITY_INTERVAL'] = '30'
          spawner.storage_capacity = '2Gi'  
      c.KubeSpawner.pre_spawn_hook = custom_limits

singleuser:
  storage:
    type: dynamic
    dynamic:
      storageClass: jupyter-nfs-storage
      pvcNameTemplate: claim-{username}
    homeMountPath: /home/jovyan/work
  nodeSelector:
    node-role: worker
    node-role.kubernetes.io/worker: "true"
  image:
    # Schimbăm imaginea generică cu cea optimizată pentru K8s
    name: quay.io/jupyterhub/k8s-singleuser-sample 
  # Important: imaginea de mai sus are deja jupyterhub instalat la versiunea corectă

  cpu:
    limit: 2
    guarantee: 1.5
  memory:
    limit: 3G
    guarantee: 1.5G
proxy:
  chp:
    nodeSelector:
      kubernetes.io/hostname: stefan-zenbook-ux425ua-um425ua


prePuller:
  hook:
    enabled: false
  continuous:
    enabled: false

scheduling:
  userScheduler:
    enabled: false

